steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
when:
  event: tag
  ref: refs/tags/v*
